import { Trial, Testimonial, FAQItem, StepProps } from "./types";

export type { StepProps };

export const STEP_NAMES = [
  "Account",
  "Personal Details",
  "Guardian",
  "Football Profile",
  "Physical",
  "Statistics",
  "Playing Style",
  "Media",
  "Documents",
  "Availability",
  "Social Media",
  "Review",
] as const;

export const COUNTRIES = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazil" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CV", label: "Cape Verde" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CR", label: "Costa Rica" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "CI", label: "Ivory Coast" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Laos" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "MX", label: "Mexico" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "KP", label: "North Korea" },
  { value: "MK", label: "North Macedonia" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "KR", label: "South Korea" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syria" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TG", label: "Togo" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
];

export const POSITIONS = [
  { value: "goalkeeper", label: "Goalkeeper" },
  { value: "right-back", label: "Right Back" },
  { value: "left-back", label: "Left Back" },
  { value: "center-back", label: "Center Back" },
  { value: "defensive-midfielder", label: "Defensive Midfielder" },
  { value: "central-midfielder", label: "Central Midfielder" },
  { value: "attacking-midfielder", label: "Attacking Midfielder" },
  { value: "right-winger", label: "Right Winger" },
  { value: "left-winger", label: "Left Winger" },
  { value: "striker", label: "Striker" },
  { value: "center-forward", label: "Center Forward" },
];

export const PREFERRED_FOOT = [
  { value: "right", label: "Right" },
  { value: "left", label: "Left" },
  { value: "both", label: "Both" },
];

export const FOOTBALL_LEVELS = [
  { value: "youth-club", label: "Youth Club" },
  { value: "school", label: "School" },
  { value: "amateur", label: "Amateur" },
  { value: "semi-professional", label: "Semi-Professional" },
  { value: "professional", label: "Professional" },
  { value: "academy", label: "Academy" },
  { value: "national-team", label: "National Team" },
];

export const CONTRACT_STATUS = [
  { value: "free-agent", label: "Free Agent" },
  { value: "contracted", label: "Contracted" },
  { value: "trial", label: "On Trial" },
  { value: "youth-contract", label: "Youth Contract" },
  { value: "released", label: "Released" },
];

export const BODY_TYPES = [
  { value: "lean", label: "Lean" },
  { value: "athletic", label: "Athletic" },
  { value: "muscular", label: "Muscular" },
  { value: "stocky", label: "Stocky" },
  { value: "slim", label: "Slim" },
];

export const FITNESS_LEVELS = [
  { value: "beginner", label: "Beginner" },
  { value: "intermediate", label: "Intermediate" },
  { value: "advanced", label: "Advanced" },
  { value: "elite", label: "Elite" },
];

export const COMMUNICATION_METHODS = [
  { value: "email", label: "Email" },
  { value: "phone", label: "Phone" },
  { value: "whatsapp", label: "WhatsApp" },
  { value: "any", label: "Any" },
];

export const RELATIONSHIP_OPTIONS = [
  { value: "parent", label: "Parent" },
  { value: "guardian", label: "Guardian" },
  { value: "grandparent", label: "Grandparent" },
  { value: "sibling", label: "Sibling" },
  { value: "uncle-aunt", label: "Uncle/Aunt" },
  { value: "coach", label: "Coach" },
  { value: "other", label: "Other" },
];

export const SAMPLE_TRIALS: Trial[] = [
  {
    id: "1",
    title: "Premier League U-21 Scout Day",
    location: "London, United Kingdom",
    date: "August 15, 2026",
    positions: ["Forward", "Midfielder", "Winger"],
    deadline: "August 1, 2026",
    description:
      "A premier scouting event targeting under-21 talent for professional club pathways across the UK.",
  },
  {
    id: "2",
    title: "La Liga Academy Open Tryouts",
    location: "Barcelona, Spain",
    date: "September 3, 2026",
    positions: ["Defender", "Goalkeeper", "Midfielder"],
    deadline: "August 20, 2026",
    description:
      "Open tryouts for aspiring academy players looking to join top-tier Spanish football programs.",
  },
  {
    id: "3",
    title: "MLS Next Pro Combine",
    location: "Austin, Texas, USA",
    date: "October 10, 2026",
    positions: ["Striker", "Right Back", "Central Midfielder"],
    deadline: "September 25, 2026",
    description:
      "Professional combine event for players seeking contracts in the MLS Next Pro league.",
  },
  {
    id: "4",
    title: "Bundesliga Talent Showcase",
    location: "Berlin, Germany",
    date: "November 22, 2026",
    positions: ["Defender", "Forward", "Goalkeeper"],
    deadline: "November 8, 2026",
    description:
      "Showcase event for talented players aiming for trials with Bundesliga and 2. Bundesliga clubs.",
  },
];

export const SAMPLE_TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Marcus Johnson",
    position: "Striker",
    quote:
      "ProScout changed my life. Within weeks of uploading my highlights, I was contacted by scouts from two professional clubs. I never thought a platform could connect me so directly to opportunities.",
    outcome: "Signed with FC United",
    initials: "MJ",
  },
  {
    id: "2",
    name: "Carlos Ramirez",
    position: "Central Midfielder",
    quote:
      "I was playing semi-professional football with no clear path forward. ProScout gave me the visibility I needed. The scout review feature helped me understand my strengths and areas to improve.",
    outcome: "Trial with Real Betis Academy",
    initials: "CR",
  },
  {
    id: "3",
    name: "Kwame Asante",
    position: "Right Back",
    quote:
      "The platform is incredibly easy to use. I uploaded my match footage, and within a month I had interest from clubs in three different countries. ProScout is the real deal.",
    outcome: "Signed with Ajax Youth",
    initials: "KA",
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    question: "How much does it cost to register?",
    answer:
      "Registration on ProScout is completely free. You can create your profile, upload videos, and submit applications at no cost. We believe every talented player deserves a chance to be seen.",
  },
  {
    question: "Who reviews my profile?",
    answer:
      "Your profile is reviewed by our team of professional scouts who have decades of experience across top European and international leagues. Each submission receives careful, individual attention.",
  },
  {
    question: "What kind of videos should I upload?",
    answer:
      "We recommend uploading highlight reels (3-5 minutes), full match footage, and any training clips that showcase your best skills. Make sure videos are clear, well-lit, and show you in action.",
  },
  {
    question: "How long does the review process take?",
    answer:
      "Our standard review process takes 7-14 business days. During peak scouting seasons, it may take slightly longer. You'll receive email notifications at every stage of the review process.",
  },
  {
    question: "Can I update my profile after submitting?",
    answer:
      "Yes, you can update your profile at any time. Simply log in, make your changes, and your updated profile will be visible to scouts on their next review cycle.",
  },
  {
    question: "What happens if a scout is interested in me?",
    answer:
      "If a scout identifies you as a potential match, you'll receive a direct notification with their contact details and trial information. From there, you can communicate directly and arrange next steps.",
  },
];
